directory: ~/Music/SynchedMusic
library: ~/.beets_data/music_library.blb

import:
    copy: no

plugins: convert

convert:
    command: ffmpeg -i $source -y -vn -aq 2 -b:v 320k $dest
    extension: mp3

