#! /bin/bash

if [[ ! -e `which ioreg` ]]; then
    echo "You're not running OSX." 2>&1
    exit 1
fi

batt_stat=`ioreg -c AppleSmartBattery`
echo $batt_stat | grep -q Capacity
if [[ $? -ne 0 ]]; then
    # battery? what battery???
    echo "bat:N/A%"
else
    echo $batt_stat | grep -q 'ExternalConnected.*Yes'
    if [[ $? -eq 0 ]]; then
        pwr_src='chg'
    else
        pwr_src='bat'
    fi
    # print remaining battery life as a %
    pct=`ioreg -c AppleSmartBattery | grep '\(Max\|Current\)Capacity' | tr '\n' ' |' | awk '{printf("%.1f\n", ($10 / $5) * 100)}'`
    echo "$pwr_src:$pct%"
fi

